# Q1

In [1]:
import numpy as np
import pandas as pd 
import operator 

ϕ = np.random.rand(40,10) 
ϕ 

array([[0.98285775, 0.22861327, 0.2155353 , 0.69905302, 0.96163025,
        0.93774583, 0.25212898, 0.11624176, 0.07535171, 0.4006872 ],
       [0.03288418, 0.46755558, 0.5368939 , 0.38641332, 0.88582387,
        0.0996581 , 0.99095146, 0.10911969, 0.66469572, 0.57075772],
       [0.07797555, 0.93863962, 0.45036215, 0.3424577 , 0.56278589,
        0.19421548, 0.47331918, 0.8559812 , 0.58364248, 0.2793681 ],
       [0.687937  , 0.67413925, 0.10721435, 0.92980381, 0.94146138,
        0.18281484, 0.94641161, 0.87386063, 0.58395466, 0.31681467],
       [0.98565116, 0.74200027, 0.21221117, 0.0850101 , 0.92027824,
        0.13497976, 0.0684633 , 0.91692181, 0.04172291, 0.18016331],
       [0.22317871, 0.17491731, 0.52326024, 0.36469722, 0.67399756,
        0.57717672, 0.07702605, 0.84505003, 0.00561707, 0.60521937],
       [0.2123321 , 0.78680102, 0.75238134, 0.48093435, 0.24223853,
        0.9075706 , 0.85343193, 0.71948684, 0.23481371, 0.66150869],
       [0.29871214, 0.22118498, 0.6704055

In [2]:
ψ = np.random.rand(40) 
ψ 

array([0.5691256 , 0.97367355, 0.36163565, 0.61499396, 0.20094453,
       0.41446826, 0.9728261 , 0.61217884, 0.82478851, 0.10816097,
       0.19055553, 0.54089227, 0.49474778, 0.64853935, 0.10199905,
       0.67033757, 0.7179117 , 0.78873191, 0.69359771, 0.77697738,
       0.62184888, 0.18957504, 0.17061917, 0.47452513, 0.6084769 ,
       0.06205211, 0.40647857, 0.28269526, 0.04475495, 0.60489697,
       0.41126688, 0.62806886, 0.33635082, 0.66676475, 0.82626921,
       0.74808235, 0.38120743, 0.58165553, 0.88030041, 0.11810996])

In [3]:
least_squares_solution, loss, rank, s = np.linalg.lstsq(ϕ, ψ, rcond=None)

In [4]:
least_squares_solution

array([ 0.151331  , -0.09123919,  0.1636601 , -0.00581427,  0.16112818,
       -0.06708893,  0.27482073,  0.06876695,  0.06165612,  0.24881903])

In [5]:
associated_loss = np.linalg.norm(np.dot(ϕ,least_squares_solution) - ψ)
associated_loss

1.5801125932724187

In [6]:
δ = np.random.rand(10) 

In [7]:
(np.dot(ϕ , (least_squares_solution + δ))).shape

(40,)

In [8]:
lhs_eq = np.dot(ϕ , (least_squares_solution + δ)) - ψ
print(np.linalg.norm(lhs_eq))

11.969014855100005


In [9]:
lhs = np.linalg.norm(lhs_eq) ** 2
lhs

143.25731660160457

In [10]:
rhs = np.linalg.norm(associated_loss) ** 2 
rhs

2.4967558074180882

 ## Thus we can see that LHS > RHS 
 ## Hence the inequality ‖Φ(θ* + δ) −ψ‖<sup>2</sup> > ‖Φθ* −ψ‖<sup>2</sup> holds true. 

In [11]:
def answer(expr):
    if expr == True:
        return "yes"

In [12]:
for i in range(1, 25): 
    δ = np.random.rand(10) 
    lhs_eq = np.dot(ϕ , (least_squares_solution + δ)) - ψ
    lhs = np.linalg.norm(lhs_eq) ** 2 
    rhs_eq = np.linalg.norm(np.dot(ϕ, least_squares_solution) - ψ) 
    rhs = np.linalg.norm(rhs_eq) ** 2 
    print( "The inequality holds? ", answer(lhs > rhs))  


The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
The inequality holds?  yes
